# Generated by Django 6.0.3 on 2026-04-02 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extraction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV')], default='json', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_hash', models.CharField(blank=True, help_text='SHA256 hash for integrity verification', max_length=64)),
                ('metadata', models.JSONField(default=dict, help_text='Export metadata including timestamp, source, etc.')),
                ('is_public', models.BooleanField(default=False, help_text='Whether file is accessible to all users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for file', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exports', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_exports', to='extraction.extractionjob')),
            ],
            options={
                'verbose_name': 'File Export',
                'verbose_name_plural': 'File Exports',
                'db_table': 'file_exports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job', 'created_at'], name='file_export_job_id_328fb5_idx'), models.Index(fields=['created_by', 'created_at'], name='file_export_created_ee9e6f_idx'), models.Index(fields=['status'], name='file_export_status_9a21b6_idx'), models.Index(fields=['is_public'], name='file_export_is_publ_731160_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoredRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(help_text='Original row number from extraction')),
                ('data', models.JSONField(help_text='Stored data after validation and processing')),
                ('original_data', models.JSONField(blank=True, default=dict, help_text='Original extracted data for audit trail')),
                ('is_modified', models.BooleanField(default=False, help_text='Whether data was modified before storage')),
                ('validation_status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('pending', 'Pending')], default='valid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_records', to='extraction.extractionjob')),
            ],
            options={
                'verbose_name': 'Stored Record',
                'verbose_name_plural': 'Stored Records',
                'db_table': 'stored_records',
                'ordering': ['job', 'row_number'],
                'indexes': [models.Index(fields=['job', 'row_number'], name='stored_reco_job_id_2ec5b8_idx'), models.Index(fields=['job', 'validation_status'], name='stored_reco_job_id_6a87d8_idx'), models.Index(fields=['created_at'], name='stored_reco_created_a3aa81_idx')],
            },
        ),
    ]
