# Generated by Django 6.0.3 on 2026-04-02 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extraction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_datasets', to=settings.AUTH_USER_MODEL)),
                ('extraction_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dataset', to='extraction.extractionjob')),
            ],
            options={
                'verbose_name': 'Data Set',
                'verbose_name_plural': 'Data Sets',
                'db_table': 'data_sets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(help_text='Row number in the dataset')),
                ('batch_number', models.IntegerField(help_text='Batch number this row came from')),
                ('original_data', models.JSONField(help_text='Original extracted data (read-only)')),
                ('current_data', models.JSONField(help_text='Current data after edits')),
                ('is_modified', models.BooleanField(default=False, help_text='Whether this row has been modified')),
                ('is_valid', models.BooleanField(default=True, help_text='Whether current data passes validation')),
                ('validation_errors', models.JSONField(blank=True, default=dict, help_text='Validation error messages by field')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='data_grid.dataset')),
            ],
            options={
                'verbose_name': 'Data Row',
                'verbose_name_plural': 'Data Rows',
                'db_table': 'data_rows',
                'ordering': ['row_number'],
                'indexes': [models.Index(fields=['dataset', 'is_modified'], name='data_rows_dataset_1a578f_idx'), models.Index(fields=['dataset', 'is_valid'], name='data_rows_dataset_a90a31_idx'), models.Index(fields=['batch_number'], name='data_rows_batch_n_652d6c_idx')],
            },
        ),
    ]
