# Generated by Django 6.0.3 on 2026-04-02 06:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('table_name', models.CharField(max_length=255)),
                ('schema_name', models.CharField(blank=True, max_length=255)),
                ('columns', models.JSONField(blank=True, default=list, help_text='List of columns to extract, empty for all')),
                ('query', models.TextField(blank=True, help_text='Custom SQL query (overrides table extraction)')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Filter conditions')),
                ('batch_size', models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('total_batches', models.IntegerField(default=0)),
                ('failed_batches', models.IntegerField(default=0)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_jobs', to='connections.connectionconfig')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extraction Job',
                'verbose_name_plural': 'Extraction Jobs',
                'db_table': 'extraction_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('row_count', models.IntegerField(default=0)),
                ('offset', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='extraction.extractionjob')),
            ],
            options={
                'verbose_name': 'Extraction Batch',
                'verbose_name_plural': 'Extraction Batches',
                'db_table': 'extraction_batches',
                'ordering': ['job', 'batch_number'],
                'unique_together': {('job', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='ExtractionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('data', models.JSONField()),
                ('is_modified', models.BooleanField(default=False)),
                ('modified_data', models.JSONField(blank=True, default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='extraction.extractionbatch')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='extraction.extractionjob')),
            ],
            options={
                'verbose_name': 'Extraction Result',
                'verbose_name_plural': 'Extraction Results',
                'db_table': 'extraction_results',
                'ordering': ['job', 'row_number'],
                'indexes': [models.Index(fields=['job', 'row_number'], name='extraction__job_id_66ac7e_idx'), models.Index(fields=['is_modified'], name='extraction__is_modi_4eb0c9_idx')],
            },
        ),
    ]
