# Generated by Django 6.0.3 on 2026-04-02 06:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('database_type', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('mongodb', 'MongoDB'), ('clickhouse', 'ClickHouse')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('database_name', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=500)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('connection_timeout', models.IntegerField(default=30, help_text='Connection timeout in seconds', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)])),
                ('max_connections', models.IntegerField(default=10, help_text='Maximum number of connections in pool', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Connection Configuration',
                'verbose_name_plural': 'Connection Configurations',
                'db_table': 'connection_configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('test', 'Test Connection'), ('extract', 'Data Extraction'), ('query', 'Query Execution'), ('error', 'Error Occurred')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='connections.connectionconfig')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connection_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Connection History',
                'verbose_name_plural': 'Connection Histories',
                'db_table': 'connection_history',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_successful', models.BooleanField()),
                ('response_time_ms', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='connections.connectionconfig')),
            ],
            options={
                'verbose_name': 'Connection Test Result',
                'verbose_name_plural': 'Connection Test Results',
                'db_table': 'connection_test_results',
                'ordering': ['-tested_at'],
            },
        ),
    ]
