# Generated by Django 4.2.11 on 2026-04-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionconfig',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
